#!/bin/bash
#
######################################################
# Kibojoe Linux					     #
# Updated 21.04.2017 10:58:31			     #
# Version 0.1-1					     #
# Name flocate ; File Locate System		     #
# Use chmod +x flocate ; /usr/bin/kibojoe	     #
# Credit Bulin Claude (Développement Sous GNU/Linux) #
# Site http://www.xcfa.tuxfamily.org/                #
# Adapted Holmes (Manjaro Brasil)		     #
# License Copyleft				     #
######################################################

gost () {
	clear
	Description=`lsb_release -d`
	release=`lsb_release -r`
	codename=`lsb_release -c`
        
	echo ""
	echo -e "                            File Locate System"
        echo ""
        echo -e "                        Locating everything for you!"
	echo -e " ┌─────────────────────────────────────────────────────────────────────────┐"        
	echo -e "      ______ _                     _          "
	echo -e "     |  ____| |                   | |         "
	echo -e "     | |__  | |     ___   ___ __ _| |_ ___    "$Description
	echo -e "     |  __| | |    / _ \ / __/ _  | __/ _ \   "$release
	echo -e "     | |    | |___| (_) | (_| (_| | ||  __/   "$codename
	echo -e "     |_|    |______\___/ \___\__ _|\__\___|   "
        echo ""
	echo ""
	echo -e "   1	Update Database"
	echo ""
	echo -e "   2	Locate for Something"
	echo ""
	echo -e "   3	Wiki mlocate"
	echo -e " └─────────────────────────────────────────────────────────────────────────┘"
	echo ""
	echo -e "              ✓ Select a number and press [Enter] ✓ e Exit"
	echo ""

	read choix
        case $choix in

              1)
		echo
                sudo updatedb
                echo
                echo -e "Done! Return to FLocate press [Enter]"
                read
                ;;
	      2)
		echo -n " ▶ Please enter what you want to locate: "
		read searchmsg
		locate "$searchmsg"
		echo 
	        echo -e "Done! Return to FLocate press [Enter]" 
	        read 
		;;
	      3)
		echo
                $BROWSER https://wiki.gentoo.org/wiki/Mlocate
                echo
                echo -e "Homepage visited! Return to FLocate press [Enter]"
                read
                ;;
	      e)
		clear && kill -9 -$PPID
		;;
	      *)
		echo "Wrong option! Wait and try again..."
                echo
                sleep 2
                clear
                ;;
	esac
}

while [[ $BoolQuit -eq 0 ]]; do
	gost
done
