#!/bin/bash
#
######################################################
# Kibojoe Linux					     #
# Updated 20.04.2017 10:58:31			     #
# Version 0.1-1					     #
# Name flocate ; File Locate System		     #
# Use chmod +x flocate ; /usr/bin/kibojoe	     #
# Credit Bulin Claude (Développement Sous GNU/Linux) #
# Site http://www.xcfa.tuxfamily.org/                #
# Adapted Holmes (Manjaro Brasil)		     #
# License Copyleft				     #
######################################################

### Set color
BLUE="\033[7;34m"
BLU="\033[1;34m"
RED="\033[1;31m"
LRED="\033[7;31m"
WHI="\033[1;37m"
NC="\033[0m"
YELLOW="\033[1;33m"
GREL="\033[7;32m"
GRE="\033[1;32m"
BoolQuit=0

### Get_key
function get_key() {
        echo ""
	echo -n "$(gettext '✓ Type a letter of command or [ q ] to quit...: ')"
	while read -r -n 1 -s answer; do
		if [[ $answer = [AaBbCcDdEeFfGgHhIiJjKkLlRrQq] ]]; then
			[[ $answer = [Aa] ]] && retval=0
			[[ $answer = [Bb] ]] && retval=1
			[[ $answer = [Cc] ]] && retval=2
			[[ $answer = [Dd] ]] && retval=3
			[[ $answer = [Ee] ]] && retval=4
			[[ $answer = [Ff] ]] && retval=5
			[[ $answer = [Gg] ]] && retval=6
			[[ $answer = [Hh] ]] && retval=7
			[[ $answer = [Ii] ]] && retval=8
			[[ $answer = [Jj] ]] && retval=9
			[[ $answer = [Kk] ]] && retval=10
			[[ $answer = [Ll] ]] && retval=11
			[[ $answer = [Rr] ]] && retval=12
			[[ $answer = [Qq] ]] && retval=13
			break
		fi
	done
	echo $answer # just a final linefeed, optics...
	echo -e "$NC"
	return $retval
}

### Print name and version
PutName () {
        echo -e " ┌─────────────────────────────────────────────────────────────────────────┐"
	echo -e " │           File Locate System - Locating everything for you!             │"
	echo -e " │                          ✤ Kibojoe Linux ✤                              │"
	echo -e " └─────────────────────────────────────────────────────────────────────────┘"
}

### Start Script
gost () {
	clear
	kernel=`/usr/bin/kernel_conky_wrapper`
	cpu=`uname -m`
	Description=`lsb_release -d`
	release=`lsb_release -r`
	codename=`lsb_release -c`
                
	echo -e ""
	echo -e "					     "
	echo -e "       _                     _		     "Kernel: $kernel
        echo -e "      | |                   | |	     "Archiecture: $cpu
        echo -e "      | |     ___   ___ __ _| |_ ___	     "
        echo -e "      | |    / _ \ / __/ _ | __/ _  \	     "$Description
        echo -e "      | |___| (_) | (_| (_| | ||  __/	     "$release
	echo -e "      |______\___/ \___\__ _|\__\___|	     "$codename
        echo -e "					     "
	echo -e ""

	PutName
	echo ""
	echo -e " [ a ] $(gettext 'Update nlocate Database')"
	echo ""
	echo -e " [ b ] $(gettext 'Locate for Something')"
	echo ""
	echo -e " [ q ] $(gettext 'Quit')"

	get_key
	case $? in

        ### Update nlocate Database
	### sudo updatedb
	0)
		echo
                sudo updatedb
                echo
                echo -e "Done! Return to FLocate press [Enter]"
                read
                ;;

	### Locate for Something
	### locate "$searchmsg"
	1)
		echo -n "▶ Please enter what you want to locate: "
		read searchmsg
		locate "$searchmsg"
		echo 
	        echo -e "Done! Return to FLocate press [Enter]" 
	        read 
		;;
	
	### Quit
	13)
		clear && kill -9 -$PPID
		PutName
		BoolQuit=1
		;;
		
	### Error
	*)
		echo -e ""
		echo -e "$RED$(gettext 'Wrong option! Wait and try again...') $NC"
		sleep 1
		;;
	esac
}

while [[ $BoolQuit -eq 0 ]]; do
	gost
done
